// Created at 02/05/2022 08:26 PM
// Developer: trungnq2710 (trungnq2710@gmail.com)

package xrest

const (
	STATUS_SUCCESS               = "SUCCESS"
	STATUS_ERROR                 = "ERROR"
	STATUS_BAD_REQUEST           = "BAD_REQUEST"
	STATUS_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	STATUS_FORBIDDEN             = "FORBIDDEN"
	STATUS_UNAUTHORIZED          = "UNAUTHORIZED"
	STATUS_NOT_FOUND             = "NOT_FOUND"
	STATUS_TOKEN_INVALID         = "TOKEN_INVALID"
	STATUS_PERMIT_DENIED         = "PERMIT_DENIED"
)
